/**
 * Seed values from `docs/frds/model_routing/token-calibration.v1.json`
 * (generated by `scripts/calibrate-token-ratio.mjs` over the benchmark
 * corpora, 22 Sep 2026). Copied here rather than imported because the doc
 * file lives outside this package (the Docker image never has it), and the
 * counter must not depend on a path that may be absent. The values are
 * pinned to the JSON by `tests/tutor/token-budget.test.ts` — a regenerated
 * calibration that changes them fails that test until this file follows.
 */

/** Framing overhead the calibration settled on: raised from 4 to 5 per message. */
export const FRAMING_PER_MESSAGE = 5;
export const FRAMING_FIXED = 3;

/**
 * `p99(reported / count) × 1.10` on the Qwen "nothink" corpus (75 turns,
 * p99 = 1.060965). Seeded into `teaching_model_calibration` as a floor; a
 * production budget breach only ever raises it.
 */
export const SEED_PROXY_RATIO: Readonly<Record<string, number>> = Object.freeze({
  'qwen:qwen3.7-flash': 1.167062,
});

/** The conservative default for a proxy model the calibration never saw. */
export const DEFAULT_PROXY_RATIO = 1.25;
