import { NextResponse } from 'next/server';

export const API_ERROR_CODES = {
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  MISSING_API_KEY: 'MISSING_API_KEY',
  MISSING_PROVIDER: 'MISSING_PROVIDER',
  MISSING_MODEL: 'MISSING_MODEL',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  PROVIDER_DISABLED: 'PROVIDER_DISABLED',
  VOXCPM_AUTO_VOICE_REQUIRES_CONTEXT: 'VOXCPM_AUTO_VOICE_REQUIRES_CONTEXT',
  INVALID_URL: 'INVALID_URL',
  REDIRECT_NOT_ALLOWED: 'REDIRECT_NOT_ALLOWED',
  TOO_MANY_REDIRECTS: 'TOO_MANY_REDIRECTS',
  CONTENT_SENSITIVE: 'CONTENT_SENSITIVE',
  UPSTREAM_ERROR: 'UPSTREAM_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  QWEN_VC_CONFIG_MISSING: 'QWEN_VC_CONFIG_MISSING',
  QWEN_VC_ENDPOINT_INVALID: 'QWEN_VC_ENDPOINT_INVALID',
  QWEN_VC_HTTP_ERROR: 'QWEN_VC_HTTP_ERROR',
  QWEN_VC_TIMEOUT: 'QWEN_VC_TIMEOUT',
  QWEN_VC_TRANSPORT_ERROR: 'QWEN_VC_TRANSPORT_ERROR',
  QWEN_VC_RESPONSE_JSON_INVALID: 'QWEN_VC_RESPONSE_JSON_INVALID',
  QWEN_VC_RESPONSE_VOICE_MISSING: 'QWEN_VC_RESPONSE_VOICE_MISSING',
  QWEN_VC_RESPONSE_AUDIO_URL_MISSING: 'QWEN_VC_RESPONSE_AUDIO_URL_MISSING',
  QWEN_VC_AUDIO_URL_INVALID: 'QWEN_VC_AUDIO_URL_INVALID',
  QWEN_VC_AUDIO_DOWNLOAD_FAILED: 'QWEN_VC_AUDIO_DOWNLOAD_FAILED',
  QWEN_VC_AUDIO_TOO_LARGE: 'QWEN_VC_AUDIO_TOO_LARGE',
  QWEN_VC_AUDIO_EMPTY: 'QWEN_VC_AUDIO_EMPTY',
  QWEN_VC_VOICE_NOT_FOUND: 'QWEN_VC_VOICE_NOT_FOUND',
  QWEN_VC_BOOTSTRAP_UNSUPPORTED: 'QWEN_VC_BOOTSTRAP_UNSUPPORTED',
  QWEN_VC_REFERENCE_AUDIO_INVALID: 'QWEN_VC_REFERENCE_AUDIO_INVALID',
  QWEN_TTS_ERROR: 'QWEN_TTS_ERROR',
  TTS_INVALID_RESPONSE: 'TTS_INVALID_RESPONSE',
  GENERATION_FAILED: 'GENERATION_FAILED',
  TRANSCRIPTION_FAILED: 'TRANSCRIPTION_FAILED',
  PARSE_FAILED: 'PARSE_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  STAGE_LOCKED: 'STAGE_LOCKED',
  // Generation contracts (Role-Specific Slide System): an unclassified /
  // misclassified slide outline, and the typed planning conflicts that replace
  // every silent runtime-scene → slide conversion.
  OUTLINE_SLIDE_SEMANTICS_INVALID: 'OUTLINE_SLIDE_SEMANTICS_INVALID',
  OUTLINE_SCENE_CONFIG_INVALID: 'OUTLINE_SCENE_CONFIG_INVALID',
  SCENE_RUNTIME_UNAVAILABLE: 'SCENE_RUNTIME_UNAVAILABLE',
  SCENE_CAP_CONFLICT: 'SCENE_CAP_CONFLICT',
  /** A generated visual did not earn an `approved` compliance verdict (fail closed). */
  VISUAL_COMPLIANCE_WITHHELD: 'VISUAL_COMPLIANCE_WITHHELD',
  // Subject-aware scientific narration (SATTS plan §14.2): the Action is not voiced.
  SATTS_E_CONTEXT_UNAVAILABLE: 'SATTS_E_CONTEXT_UNAVAILABLE',
  SATTS_E_EMPTY_RESULT: 'SATTS_E_EMPTY_RESULT',
  SATTS_E_SEGMENT_UNSPLITTABLE: 'SATTS_E_SEGMENT_UNSPLITTABLE',
  SATTS_E_PROVIDER_INCOMPLETE: 'SATTS_E_PROVIDER_INCOMPLETE',
  SATTS_E_PROVIDER_TRUNCATED: 'SATTS_E_PROVIDER_TRUNCATED',
  SATTS_E_PROVIDER_FAILED: 'SATTS_E_PROVIDER_FAILED',
  SATTS_E_JOIN_FAILED: 'SATTS_E_JOIN_FAILED',
  /** Pronunciation diagnostics need an owner or editor grant (learners are refused). */
  SATTS_DIAGNOSTICS_FORBIDDEN: 'SATTS_DIAGNOSTICS_FORBIDDEN',
  SATTS_STAGE_NOT_FOUND: 'SATTS_STAGE_NOT_FOUND',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export interface ApiErrorBody {
  success: false;
  errorCode: ApiErrorCode;
  error: string;
  details?: string;
}

export function apiError(
  code: ApiErrorCode,
  status: number,
  error: string,
  details?: string,
): NextResponse<ApiErrorBody> {
  return NextResponse.json(
    {
      success: false as const,
      errorCode: code,
      error,
      ...(details ? { details } : {}),
    },
    { status },
  );
}

export function apiSuccess<T extends Record<string, unknown>>(data: T, status = 200): NextResponse {
  return NextResponse.json({ success: true, ...data }, { status });
}
